// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6cFjuLeo5wcsmGdjkGwU6
// Component: 0ZmXSPBwd1DS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: DwYLxxR6FM2H/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";

import { useScreenVariants as useScreenVariantsuI1HQw2QRBwD } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: uI1hQw2qRBwD/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6cFjuLeo5wcsmGdjkGwU6/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 0ZmXSPBwd1DS/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 8dWY6q-cxdHa/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: qHDe3SKps_Kk/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  usp?: Flex__<"a"> & Partial<LinkProps>;
  usp2?: Flex__<"a"> & Partial<LinkProps>;
  usp3?: Flex__<"a"> & Partial<LinkProps>;
  footer?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsuI1HQw2QRBwD()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__zqqXj)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__m6TwS)}
                displayHeight={"540px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/amg/images/frame60Png5.png",
                  fullWidth: 579,
                  fullHeight: 497,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___20ImB
                )}
              >
                {"Dipacu oleh Passion, Diproses dengan Presisi"}
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__yPftu)}
                color={"sand"}
                shape={"rounded"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tiWXc
                  )}
                >
                  {"GET QUOTATION"}
                </div>
              </Button>
            </div>
            {(() => {
              const child$Props = {
                arrows: false,
                autoplay: true,
                autoplaySpeed: 3000,
                beforeChange: generateStateOnChangePropForCodeComponents(
                  $state,
                  "currentSlide",
                  ["sliderCarousel", "currentSlide"],
                  SliderWrapper_Helpers
                ),
                centerMode: false,
                className: classNames("__wab_instance", sty.sliderCarousel),
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel__slider"]
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel"}
                  data-plasmic-override={overrides.sliderCarousel}
                  {...child$Props}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___9Hs2L)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ji3As)}
                      displayHeight={"540px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      height={"600"}
                      src={{
                        src: "/plasmic/amg/images/frame60Png5.png",
                        fullWidth: 579,
                        fullHeight: 497,
                        aspectRatio: undefined
                      }}
                    />

                    <Button
                      className={classNames("__wab_instance", sty.button__jSJv)}
                      color={"sand"}
                      shape={"rounded"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eb196
                        )}
                      >
                        {"GET QUOTATION"}
                      </div>
                    </Button>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tmawm
                      )}
                    >
                      {"Dipacu oleh Passion, Diproses dengan Presisi"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tsqJe)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pVfSq
                      )}
                    >
                      {"Temukan Bahan Terbaik Untuk Produkmu"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2Mqmy)}
                      displayHeight={"540px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/amg/images/frame61Png.png",
                        fullWidth: 579,
                        fullHeight: 497,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mpt9J)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ojmMl
                      )}
                    >
                      {"Memberikan Kualitas Sejak 1990"}
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___37KLr)}
                      displayHeight={"540px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={{
                        src: "/plasmic/amg/images/frame62Png.png",
                        fullWidth: 579,
                        fullHeight: 497,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </SliderWrapper>
              );
            })()}
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1RhoR)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__jjtQx
                )}
              >
                {"OVERVIEW"}
              </h3>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3___1Djo0
                )}
              >
                {"Memberikan Kualitas Sejak 1990"}
              </h3>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bFnh1
                )}
              >
                {
                  "Perusahaan kami muncul pada tahun 1990, didorong oleh satu mesin rajut, yang dirakit dengan cermat oleh pendiri kami. Saat ini, sebagai bukti komitmen kami terhadap kualitas dan inovasi, kami masih menggunakan mesin tersebut, melestarikan warisannya dalam menghasilkan kertas yang unggul."
                }
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__lfRkE)}
                color={"sand"}
                shape={"rounded"}
              >
                {"LEBIH LANJUT"}
              </Button>
            </Stack__>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__dRmHg)}
              displayHeight={"200px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/amg/images/_20211007160317Jpg.jpg",
                fullWidth: 980,
                fullHeight: 680,
                aspectRatio: undefined
              }}
            />

            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__iarD)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__jqGk6
                )}
              >
                {"PRODUCTS"}
              </h3>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3___3OUgB
                )}
              >
                {"Pilihan Terbaik Anda untuk Packaging"}
              </h3>
              <Button
                className={classNames("__wab_instance", sty.button__xwTfe)}
                color={"sand"}
                shape={"rounded"}
              >
                {"LIHAT SEMUA PRODUK"}
              </Button>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zdGw2)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p7Lau)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__sNx2Q
                    )}
                    component={Link}
                    href={`/new-page`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__tocf5)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"auto"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"180px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/amg/images/group18Png.png",
                        fullWidth: 800,
                        fullHeight: 800,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___0BNR)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"180px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/group17Png.png",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qoAqQ)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hBpi)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"auto"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"180px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/group15Png2.png",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pDusv)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"180px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/group16Png.png",
                      fullWidth: 800,
                      fullHeight: 800,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__eCAk3)}
            >
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__qgVzB
                )}
              >
                {"EXELLENCE"}
              </h3>
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__auSrO
                )}
              >
                {"Kenapa Memilih Kami?"}
              </h3>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nojyG)}
              >
                <Stack__
                  as={PlasmicLink__}
                  data-plasmic-name={"usp"}
                  data-plasmic-override={overrides.usp}
                  hasGap={true}
                  className={classNames(projectcss.all, projectcss.a, sty.usp)}
                  component={Link}
                  platform={"nextjs"}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___7D6Xo)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__njoNs
                      )}
                    >
                      {"State-of-the-art Machines"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7YqOo
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eafAx
                        )}
                      >
                        {"Make a high production capacity a reality."}
                      </div>
                    </Stack__>
                  </Stack__>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__g7SGp)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"80px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/_416260Png.png",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
                <Stack__
                  as={PlasmicLink__}
                  data-plasmic-name={"usp2"}
                  data-plasmic-override={overrides.usp2}
                  hasGap={true}
                  className={classNames(projectcss.all, projectcss.a, sty.usp2)}
                  component={Link}
                  platform={"nextjs"}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__kv4E)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Xtwr
                      )}
                    >
                      {"The Best Cardboard Boxes Quality"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pA0Bo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wkzZk
                        )}
                      >
                        {"Quality cardboard boxes outcome."}
                      </div>
                    </Stack__>
                  </Stack__>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__piHmh)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"80px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/packagepng.png",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
                <Stack__
                  as={PlasmicLink__}
                  data-plasmic-name={"usp3"}
                  data-plasmic-override={overrides.usp3}
                  hasGap={true}
                  className={classNames(projectcss.all, projectcss.a, sty.usp3)}
                  component={Link}
                  platform={"nextjs"}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rJnFp)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sUa3
                      )}
                    >
                      {"Better Printing Cut Results"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__nppuk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jQMG
                        )}
                      >
                        {"A neat and clean printing cut results."}
                      </div>
                    </Stack__>
                  </Stack__>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__z7CQk)}
                    displayHeight={"80px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"80px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/amg/images/laserpng.png",
                      fullWidth: 512,
                      fullHeight: 512,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              hasGap={true}
              className={classNames(projectcss.all, sty.footer)}
            >
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__dvL7B
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__n4M3Z)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"200px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/amg/images/asset11Svg.svg",
                    fullWidth: 127.08,
                    fullHeight: 34.07,
                    aspectRatio: 3.729968
                  }}
                />
              </PlasmicLink__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__v9ZzL
                )}
              >
                {
                  "PT Mulia Grand Manufacture was established in August 2015 in Boboh \u2013 Menganti area. Our company is specialized in the production of corrugated cardboard and cardboard boxes."
                }
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__hpgz3)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wPIen)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h8Goz
                    )}
                  >
                    {"Company"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uhuy1
                    )}
                  >
                    {"Home"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rnahe
                    )}
                  >
                    {"Our Business"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lH5H7
                    )}
                  >
                    {"About Us"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xVzXy)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ragvJ
                    )}
                  >
                    {"Join With Us"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pjgKl
                    )}
                  >
                    {"Carrer"}
                  </div>
                </Stack__>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hLHc)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ukwD4
                  )}
                >
                  {"Quick Contact"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gccXk
                  )}
                >
                  {
                    "If you have any questions or need help, feel free to contact us"
                  }
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__gpbQb)}
                  color={"sand"}
                  shape={"rounded"}
                >
                  {"GET INQUIRY"}
                </Button>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__p66Oe)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z2LpA
                  )}
                >
                  {"031 7997 0889"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1GZlS
                  )}
                >
                  {
                    "Jl. Raya Boboh No.89, RT. 05/RW 03, Desa Boboh Kec. Menganti, Kabupaten Gresik, Jawa Timur 61174"
                  }
                </div>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__k8GlR
                )}
              >
                {"Copyright 2022 \u00a9 PT Artaniaga Megah Gemilang"}
              </div>
            </Stack__>
          </section>
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            brand={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__qr6Rv
                )}
                component={Link}
                href={"#"}
                platform={"nextjs"}
              >
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__b1Q4P
                  )}
                  component={Link}
                  href={`/`}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__d8U6)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={{
                      src: "/plasmic/amg/images/asset10Svg.svg",
                      fullWidth: 127.08,
                      fullHeight: 34.07,
                      aspectRatio: 3.729968
                    }}
                  />
                </PlasmicLink__>
              </PlasmicLink__>
            }
            className={classNames("__wab_instance", sty.navigationBar)}
            closeButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__iD6D)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/close.svg"}
              />
            }
            itemsGap={8}
            menuItems={
              <React.Fragment>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__gygJb
                  )}
                  component={Link}
                  href={"/"}
                  platform={"nextjs"}
                >
                  {"Home"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__dfn5R
                  )}
                  component={Link}
                  href={"/"}
                  platform={"nextjs"}
                >
                  {"About"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__jzlH
                  )}
                  component={Link}
                  href={"/"}
                  platform={"nextjs"}
                >
                  {"Contact"}
                </PlasmicLink__>
              </React.Fragment>
            }
            openButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__kj7I)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                height={""}
                src={"https://static1.plasmic.app/menu.svg"}
                width={"32"}
              />
            }
            responsiveBreakpoint={768}
          />

          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__eyMw3)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "sliderCarousel",
    "usp",
    "usp2",
    "usp3",
    "footer",
    "navigationBar"
  ],
  section: ["section", "sliderCarousel", "usp", "usp2", "usp3", "footer"],
  sliderCarousel: ["sliderCarousel"],
  usp: ["usp"],
  usp2: ["usp2"],
  usp3: ["usp3"],
  footer: ["footer"],
  navigationBar: ["navigationBar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  sliderCarousel: typeof SliderWrapper;
  usp: "a";
  usp2: "a";
  usp3: "a";
  footer: "div";
  navigationBar: typeof NavigationBar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    usp: makeNodeComponent("usp"),
    usp2: makeNodeComponent("usp2"),
    usp3: makeNodeComponent("usp3"),
    footer: makeNodeComponent("footer"),
    navigationBar: makeNodeComponent("navigationBar"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
